### ISSUE TITLE
No package matching 'node' is available

### ISSUE THREAD

**Issue by nfortea** [agoravoting/agora-dev-box#118]
When I execute:
`time sudo ansible-playbook -i inventory playbook.yml`

I receive next error:
TASK [Packages, Installing packages] *******************************************
failed: [localhost] (item=[u'git', u'htop', u'curl', u'postgresql-9.4', u'postgresql-9.4-repmgr', u'mercurial', u'nginx', u'supervisor', u'node', u'libffi-dev', u'virtualenvwrapper', u'libjpeg8-dev', u'libpq-dev=9.4*', u'libpq5=9.4*', u'python-psycopg2', u'python3-pip', u'python3', u'python-setuptools', u'build-essential', u'python-dev', u'vim', u'libgmp-dev', u'make', u'm4', u'p7zip-full']) => {"failed": true, "item": ["git", "htop", "curl", "postgresql-9.4", "postgresql-9.4-repmgr", "mercurial", "nginx", "supervisor", "node", "libffi-dev", "virtualenvwrapper", "libjpeg8-dev", "libpq-dev=9.4*", "libpq5=9.4*", "python-psycopg2", "python3-pip", "python3", "python-setuptools", "build-essential", "python-dev", "vim", "libgmp-dev", "make", "m4", "p7zip-full"], "msg": "No package matching 'node' is available"}

**Comment by Findeton** [comment]
Agora is normally deployed on a vm or on a system with Ubuntu trusty 14.04 LTS , where you can find the 'node' package.

**Comment by nfortea** [comment]
Exactly. I upgrade our machine to 16.04.

I resolved that adding to /etc/apt/sources.list this line:
`deb http://es.archive.ubuntu.com/ubuntu/ trusty universe`
but in some stages later received that:

TASK [Packages, upgrade postgresql db to 9.4] **********************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "cd && /usr/lib/postgresql/9.4/bin/pg_upgrade -b /usr/lib/postgresql/9.3/bin -B /usr/lib/postgresql/9.4/bin -d /etc/postgresql/9.3/main -D /etc/postgresql/9.4/main", "delta": "0:00:00.012415", "end": "2017-02-11 12:17:40.986472", "failed": true, "rc": 1, "start": "2017-02-11 12:17:40.974057", "stderr": "", "stdout": "Finding the real data directory for the new cluster         ok\n\ncheck for \"/usr/lib/postgresql/9.3/bin\" failed: No such file or directory\n\nFailure, exiting", "stdout_lines": ["Finding the real data directory for the new cluster         ok", "", "check for \"/usr/lib/postgresql/9.3/bin\" failed: No such file or directory", "", "Failure, exiting"], "warnings": []}

I think to start from beginning, reinstalling vm to 14.04.
