### ISSUE TITLE
Error connecting authorities

### ISSUE THREAD

**Issue by nfortea** [agoravoting/agora-dev-box#187]
Hi,
We are following the tutorial on [production deployment](https://github.com/agoravoting/agora-dev-box/blob/master/doc/production_deployment.md) and when trying to connect the authorities, we get the following error when running 'eotest':
`> Starting server on port 8000

using the following authorities:
 1. auth1.zaragozaencomun.com (this is us, acting as orchestra director)
 2. auth2.zaragozaencomun.com

> Creating election 7824
Traceback (most recent call last):
  File "/usr/bin/eotest.py", line 490, in <module>
    main(sys.argv[1:])
  File "/usr/bin/eotest.py", line 485, in main
    eval(command + "(args)")
  File "<string>", line 1, in <module>
  File "/usr/bin/eotest.py", line 452, in full
    pkFile = create(args)
  File "/usr/bin/eotest.py", line 361, in create
    startElection(electionId, startUrl, startData)
  File "/usr/bin/eotest.py", line 279, in startElection
    r = session.request('post', url, data=json.dumps(data), verify=CALIST, cert=(CERT, KEY))
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='auth1.zaragozaencomun.com', port=5000):Max retries exceeded with url: /public_api/election (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa30a171490>: Failed to establish a new connection: [Errno 113] No route to host',))
`
We try to regenerate certs unsuccessfully obtaining same error.
Any tip?

**Comment by edulix** [comment]
This is either a name resolution issue, see the "No route to host". Usually authorities connect to each other by hostname without using DNS for security. Is auth1.zaragozaencomun.com in /etc/hosts? Was the eopeer package of the peer dumped with "--private-ip" if they are connected through a private network? Please take a look at https://github.com/agoravoting/agora-dev-box/blob/master/doc/production_deployment.md

**Comment by nfortea** [comment]
That's it. I revised our /etc/hosts and we can continue.
Now we receive SNIMissingWarning and InsecurePlatformWarning message, but this is another matter.
Thank you @edulix
