### ISSUE TITLE
[FIX][NEXT] Config files unreadable

### ISSUE THREAD

**Issue by Endika** [agoravoting/agora-dev-box#19]
When executed `vagrant provision` in this part https://github.com/agoravoting/agora-dev-box/blob/next/agora-elections/main.yml#L14

'templates' folder not exist. I execute code in manual mode

```
cp /vagrant/agora-elections/templates/application.local.conf /home/agoraelections/agora-elections/conf/application.local.conf
chmod 0644  /home/agoraelections/agora-elections/conf/application.local.conf
chown agoraelections:  /home/agoraelections/agora-elections/conf/application.local.conf
```

and repear for test.local.conf file
- The same case to `run.sh` file
  https://github.com/agoravoting/agora-dev-box/blob/next/agora-elections/main.yml#L70
- The same case to `sentryconf.yml` file
  https://github.com/agoravoting/agora-dev-box/blob/next/sentry/sentryconf.yml#L2

**Comment by edulix** [comment]
This is an old issue that is not applicable anymore I think. Please reopen if it is.
