### ISSUE TITLE
Deployment instruction not work on the `Test the connection between the authorities` step

### ISSUE THREAD

**Issue by omidraha** [agoravoting/agora-dev-box#77]
Hi,
I follow the [dev deployment](https://github.com/agoravoting/agora-dev-box/blob/3.2.0/doc/devel_deployment.md) instruction,

But my try failed on the ``Test the connection between the authorities`` [step](https://github.com/agoravoting/agora-dev-box/blob/3.2.0/doc/devel_deployment.md#test-the-connection-between-the-authorities) by this error:

```
> Creating election 2846
Traceback (most recent call last):
  File "/usr/bin/eotest.py", line 475, in <module>
    main(sys.argv[1:])
  File "/usr/bin/eotest.py", line 470, in main
    eval(command + "(args)")
  File "<string>", line 1, in <module>
  File "/usr/bin/eotest.py", line 437, in full
    pkFile = create(args)
  File "/usr/bin/eotest.py", line 346, in create
    startElection(electionId, startUrl, startData)
  File "/usr/bin/eotest.py", line 268, in startElection
    r = requests.post(url, data=json.dumps(data), verify=False, cert=(CERT, KEY))
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 465, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='agoravoting.com', port=5000): Max retries exceeded with url: /public_api/election (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 403 Forbidden',)))
Connection to 127.0.0.1 closed.

```

I don't change any configuration, just follow the instruction step by step.
I also read the [deployment troubleshooting](https://github.com/agoravoting/agora-dev-box/blob/3.2.0/doc/deployment_troubleshooting.md), but i have no idea how to fix this.

**Comment by Findeton** [comment]
Hi @omidraha  I can see on the trace that it says HTTPSConnectionPool(host='agoravoting.com' . This indicates to me that you might have the wrong config.yml configuration. I'm guessing you are executing this on the auth1 folder:

    auth1 $ vagrant ssh -c "sudo eotest full --vmnd --vcount 100"

But perhaps you have the config.host parameter set to agoravoting.com on auth1/config.yml which would indicate that you didn't do this step from the documentation:

    auth1 $ cp doc/devel/auth1.config.yml config.yml

So you should follow all the steps from the "Base provisioning" step onwards again. Please let me know if this helps :)

**Comment by omidraha** [comment]
You right, i ignore this `Base provisioning` [step](https://github.com/agoravoting/agora-dev-box/blob/3.2.0/doc/devel_deployment.md#base-provisioning), because on note of this part of docs:

> Although recommended, this step can be ignored.

Ok, i clean the system and try again with following all steps, now i get this error again on the `Test the connection between the authorities` [step](https://github.com/agoravoting/agora-dev-box/blob/3.2.0/doc/devel_deployment.md#test-the-connection-between-the-authorities):

```
or@debian ...prj/git/auth1 % vagrant ssh -c "sudo eotest full --vmnd --vcount 100"
> Starting server on port 8000

using the following authorities:
 1. auth1 (this is us, acting as orchestra director)
 2. auth2


> Creating election 7557
Traceback (most recent call last):
  File "/usr/bin/eotest.py", line 475, in <module>
    main(sys.argv[1:])
  File "/usr/bin/eotest.py", line 470, in main
    eval(command + "(args)")
  File "<string>", line 1, in <module>
  File "/usr/bin/eotest.py", line 437, in full
    pkFile = create(args)
  File "/usr/bin/eotest.py", line 346, in create
    startElection(electionId, startUrl, startData)
  File "/usr/bin/eotest.py", line 268, in startElection
    r = requests.post(url, data=json.dumps(data), verify=False, cert=(CERT, KEY))
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 465, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='auth1', port=5000): Max retries exceeded with url: /public_api/election (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 403 Forbidden',)))
Connection to 127.0.0.1 closed.
```

**Comment by Findeton** [comment]
Hi @omidraha, sorry for the late response. I'm guessing that you are using the 'next' branch, as the tutorial suggests. agora-dev-box refers to the other repos on the file repos.yml and it was referencing the master branch for all the other repos by default. I've fixed that now, so you only have to execute:

```
$ git pull
$ git checkout repos.yml
$ vagrant provision
```

Do that on the three folders of your devel deployment (agora, auth1, auth2) and it should fix it. Or you can start the deployment tutorial from scratch after updating agora-dev-box next branch using git pull. Please let me know if this worked for you

**Comment by omidraha** [comment]
Thanks,
I try from the beginning of tutorial again and it worked for me now.
Indeed it related to `vagrant-proxyconf`.

More details about my problem with `vagrant-proxyconf`:

- I need to enable that for downloading some package, 
- I need to ignore that for downloading packages from `pypi.python.org`, because `Agora` currently use old version of `pip` and `pyOpenSSL` and i got this error `SysCallError: (-1, 'Unexpected EOF')` when use that.
- I need to ignore that for this local network communication between auth1 and auth2.

**Comment by omidraha** [comment]
After successfully installation of `Agora`, and create one demo election by admin web panel,
Now i have one question about sending email configuration,
Where is the SMTP configuration?

**Comment by edulix** [comment]
The SMTP configuration is in the config.yml ansible configuration file.

**Comment by Findeton** [comment]
You can access the list of sent or failed to be sent emails/sms entering sentry (normally on port 9090). Once you enter sentry (using the user/pass from the sentry entry on config.yml), the messages are on Project AgoraVoting: Join the project AgoraVoting by clicking on Organizations>Projects&Teams>All Teams>AgoraVoting (Join Team). Then to view the messages go back to Organizations>Dashboard>Projects>AgoraVoting.

**Comment by omidraha** [comment]
Thanks @edulix,
But there is no option for `SMTP` password on the email config [section](https://github.com/agoravoting/agora-dev-box/blob/3.2.0/doc/devel/agora.config.yml#L337).

Thanks @Findeton,
It worked, I think it's good idea if you add your comment to development instruction tutorial.
